// content/api/inventory-samples.js
//
// Submits ONE create-inventory-sample request and returns a normalized result.
// Used only by the guarded M3 live test (single POST). The orchestrator owns the
// loop, the in-flight latch, and confirmation — this helper does exactly one
// POST and never retries.
//
// Why a dedicated helper (not cdd-api.js): cdd-api.fetchJson forces
// `Content-Type: application/json`. The create endpoint is multipart/form-data,
// where the boundary MUST be generated by the browser from the FormData. So we
// pass the FormData as the body and DO NOT set Content-Type ourselves.
//
// Session/CSRF: same-origin fetch with credentials:"include" sends the CDD
// cookie; the CSRF token is read from the page meta (as cdd-api does) and sent
// as X-CSRF-Token, plus X-Requested-With to match CDD's own request.
//
// Must not: swallow CDD's error text, retry, or loop.

import { getCsrfToken } from "./cdd-api.js";

export async function createInventorySample(url, formData, method = "POST") {
    if (!url) return { ok: false, status: 0, errorText: "No target URL" };

    const csrf = getCsrfToken();
    let res;
    try {
        res = await fetch(url, {
            method,
            credentials: "include",
            headers: {
                Accept: "application/json, text/plain, */*",
                "X-Requested-With": "XMLHttpRequest",
                ...(csrf ? { "X-CSRF-Token": csrf } : {}),
                // Intentionally NO Content-Type: the browser sets
                // multipart/form-data; boundary=... from the FormData body.
            },
            body: formData,
        });
    } catch (err) {
        return { ok: false, status: 0, errorText: String(err?.message || err) };
    }

    const text = await res.text().catch(() => "");
    let json = null;
    try {
        json = text ? JSON.parse(text) : null;
    } catch {
        /* non-JSON error body is surfaced as text below */
    }

    if (!res.ok) {
        return {
            ok: false,
            status: res.status,
            errorText: text || `HTTP ${res.status}`,
            raw: json,
        };
    }

    // create_sample_from_debit responds with the updated PARENT sample; the
    // sample just created is the newest inventory event carrying a child id
    // (events come back newest-first). The plain create responds with the new
    // sample itself, so this only kicks in on the debit endpoint.
    if (/create_sample_from_debit/.test(url)) {
        const childEvent = Array.isArray(json?.inventory_events)
            ? json.inventory_events.find((e) => e?.child_sample_id != null)
            : null;
        if (childEvent) {
            return {
                ok: true,
                status: res.status,
                sampleId: childEvent.child_sample_id,
                sampleIdentifier: childEvent.child_sample_name ?? null,
                location: null,
                raw: json,
            };
        }
    }

    return {
        ok: true,
        status: res.status,
        sampleId: json?.id ?? null,
        sampleIdentifier: json?.sample_identifier ?? null,
        location: json?.location ?? null,
        raw: json,
    };
}
