export const EVENT_SOURCE = "CDD_STOICH_TOOLS";

export const EVENTS = {
  REACTION_VISIBILITY: "REACTION_VISIBILITY",
  SAMPLE_DATA: "SAMPLE_DATA",
  PRINT_DATA: "PRINT_DATA",
  PRINT_REQUEST: "PRINT_REQUEST"
};