// content/features/panel-print.js
import { escapeHtml } from "../utils/dom.js";
import { EVENT_SOURCE, EVENTS } from "../../shared/event-types";
import { getVisibleSamples } from "./panel-contents.js";
import { isShowProductsEnabled } from "../../shared/show-products-flag.js";
import {
    SAMPLE_PANEL_FIELDS,
    resolveFieldValue,
    getCustomFieldsFromSample,
} from "../../shared/sample-panel-fields.js";
import { readElnEntryId } from "../utils/eln-entry-id.js";

// The same line the stoichiometry sheet prints, so a sheet found in a folder
// a year later says where it came from.
export const PRINT_FOOTER_TEXT =
    "Custom print layout generated by CDD Stoichiometric Table Tools. Written by Matus Drexler, IOCB Prague & PharmTheon";

// The entry's title as CDD shows it, from the same field the tab-title
// override reads. Empty off an entry.
function readElnEntryTitle() {
    const el = document.querySelector('[data-autotest-id="title"]');
    return (el?.value ?? el?.textContent ?? "").trim();
}

// Build print columns from the same enabled fields the floating panel uses:
// enabled static registry fields first, then enabled custom fields. A column is
// kept only if at least one sample actually has a value for it.
export function buildPrintColumns(samples, visibleFields) {
    const columns = [];

    for (const field of SAMPLE_PANEL_FIELDS) {
        if (!visibleFields[field.key]) continue;
        columns.push({
            label: field.label,
            getText: (sample) => resolveFieldValue(field, sample)?.text ?? "",
        });
    }

    // Custom field values, precomputed per sample for direct lookup.
    const customMaps = samples.map((sample) => {
        const map = {};
        for (const field of getCustomFieldsFromSample(sample)) {
            map[field.key] = field.value;
        }
        return map;
    });

    const customKeys = [];
    for (const map of customMaps) {
        for (const key of Object.keys(map)) {
            if (visibleFields[key] && !customKeys.includes(key)) customKeys.push(key);
        }
    }

    for (const key of customKeys) {
        const label = key.includes(":") ? key.slice(key.indexOf(":") + 1) : key;
        columns.push({
            label,
            getText: (sample, index) => {
                const value = customMaps[index]?.[key];
                return value == null ? "" : String(value);
            },
        });
    }

    // Drop columns where no sample has any data.
    return columns.filter((column) =>
        samples.some((sample, index) => column.getText(sample, index) !== "")
    );
}

export function printPanel(visibleFields = {}) {
    // Whatever the panel is showing, mentions included — not
    // STATE.lastPayload, which holds only the stoichiometry rows and would
    // quietly drop everything linked in the entry's text.
    const visible = getVisibleSamples();
    if (!visible.length) {
        alert("No sample data available.");
        return;
    }

    // Products only when the option is on; the Type column appears only
    // when there is a product to label.
    const showProducts = isShowProductsEnabled();
    const samples = visible.filter((s) => showProducts || !s.isProduct);
    const anyProduct = samples.some((s) => s.isProduct);
    const columns = buildPrintColumns(samples, visibleFields);

    const headHtml = ["Reaction", ...(anyProduct ? ["Type"] : []), ...columns.map((c) => c.label)]
        .map((label) => `<th>${escapeHtml(label)}</th>`)
        .join("");

    const rowsHtml = samples
        .map((sample, index) => {
            const cells = [
                sample.reactionLabel || "",
                ...(anyProduct ? [sample.isProduct ? "Product" : ""] : []),
                ...columns.map((column) => column.getText(sample, index)),
            ];
            return `<tr>${cells.map((value) => `<td>${escapeHtml(value)}</td>`).join("")}</tr>`;
        })
        .join("");

    // Same header as the stoichiometry sheet: the entry's title on the left,
    // its ID on the right, then where and when it was printed.
    const identifier = escapeHtml(readElnEntryId() || "Unknown experiment");
    const title = escapeHtml(readElnEntryTitle() || "Samples");

    const html = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>${identifier} - ${title}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            padding: 24px;
            color: #111;
        }
        .header {
            display: flex;
            justify-content: space-between;
            align-items: flex-start;
            gap: 16px;
            margin-bottom: 8px;
        }
        .header-left {
            flex: 1;
            min-width: 0;
        }
        .header-right {
            flex: 0 0 auto;
            text-align: right;
            padding-left: 16px;
        }
        .title {
            font-size: 20px;
            font-weight: 700;
            line-height: 1.2;
        }
        .subtitle {
            margin-top: 2px;
            font-size: 11px;
            text-transform: uppercase;
            letter-spacing: 0.08em;
            color: #6b7280;
        }
        .experiment-label {
            font-size: 10px;
            text-transform: uppercase;
            letter-spacing: 0.08em;
            color: #6b7280;
            margin-bottom: 2px;
        }
        .experiment-id {
            font-size: 15px;
            font-weight: 700;
            color: #111827;
            line-height: 1.2;
        }
        .meta {
            font-size: 11px;
            color: #666;
            margin-bottom: 14px;
        }
        .print-footer {
            margin-top: 24px;
            padding-top: 8px;
            border-top: 1px solid #d1d5db;
            font-size: 9px;
            color: #9ca3af;
            text-align: center;
        }
        table {
            border-collapse: collapse;
            width: 100%;
            font-size: 12px;
        }
        th, td {
            border: 1px solid #ccc;
            padding: 6px 8px;
            text-align: left;
            vertical-align: top;
        }
        th {
            background: #f3f4f6;
        }
    </style>
</head>
<body>
    <div class="header">
        <div class="header-left">
            <div class="title">${title}</div>
            <div class="subtitle">Samples panel</div>
        </div>
        <div class="header-right">
            <div class="experiment-label">Experiment ID</div>
            <div class="experiment-id">${identifier}</div>
        </div>
    </div>
    <div class="meta">
        <div><strong>Source:</strong> ${escapeHtml(location.href)}</div>
        <div><strong>Printed:</strong> ${escapeHtml(new Date().toLocaleString())}</div>
        <div><strong>Rows:</strong> ${samples.length}</div>
    </div>
    <table>
        <thead>
            <tr>${headHtml}</tr>
        </thead>
        <tbody>
            ${rowsHtml}
        </tbody>
    </table>
    <div class="print-footer">${escapeHtml(PRINT_FOOTER_TEXT)}</div>
</body>
</html>
`;

    window.postMessage({
        source: EVENT_SOURCE,
        type: EVENTS.PRINT_REQUEST,
        payload: { html }
    }, "*");
}